version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: spp-rails-dev
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: spp_rails_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - spp-rails-dev:/var/lib/postgresql/data

volumes:
  spp-rails-dev:
