default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  username: postgres
  password: postgres
  host: localhost
  port: 5432

development:
  <<: *default
  database: spp_rails_dev

test:
  <<: *default
  database: spp_rails_test

production:
  <<: *default
  database: spp_rails_prod
